"Save, load, and apply gpkit substitutions via TOML files."

import tomllib
import warnings
from pathlib import Path

from ..nomials.map import DIMLESS_QUANTITY
from ..units import qty
from ._parser import TomlParseError, _parse_var_spec
from ._printer import _emit_lines

# Marker key written to every subs file so load_subs can reject wrong files.
_GPKIT_SUBS_KEY = "_gpkit_subs"


def _format_subs_number(v):
    """Format a float for a subs file, preserving full round-trip precision.

    Uses repr() rather than :.4g so that parameter values with more than 4
    significant figures (e.g. g = 9.80665 m/s²) are not silently truncated.
    Clean integers are still written without a decimal point (5000, not 5000.0).
    """
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float) and v == int(v) and abs(v) < 1e15:
        return str(int(v))
    return repr(v)


def _lineage_path(model):
    """Return the dotted class-name path for a model, e.g. 'Mission.Aircraft'."""
    return ".".join(name for (name, _) in model.lineage)


def _val_to_float(val, vk):
    """Convert a substitution value to a plain float in the variable's units."""
    if hasattr(val, "hmap"):  # constant Monomial or future GPkitUnit wrapper (#156)
        assert not any(
            val.hmap.keys()
        ), "substitution value should not contain variables"
        (val,) = val.hmap.to(vk.units or DIMLESS_QUANTITY).values()
    return float(val)


def save_subs(model, path=None):
    """Serialize model substitutions to a TOML file grouped by model lineage.

    Walks the model tree (root first, then depth-first children) and emits one
    TOML section per model that has substituted variables.  Each section header
    is the model's lineage class-name path, e.g. ``[Mission.Aircraft]``.

    Parameters
    ----------
    model : Model
        The root model whose ``substitutions`` to serialize.
    path : str or Path, optional
        If given, the TOML string is also written to this file.

    Returns
    -------
    str
        The generated TOML string.
    """
    lines = [
        "# gpkit substitutions — generated by gpkit.toml.save_subs()",
        "# Edit values and apply with gpkit.toml.apply_subs(model, path)",
        f"{_GPKIT_SUBS_KEY} = true",
        "",
    ]

    for m in [model] + list(model.walk()):
        if not m.lineage:
            continue
        path_str = _lineage_path(m)

        var_lines = []
        for vk in sorted(m.unique_varkeys, key=lambda k: k.name):
            if vk not in m.substitutions:
                continue
            val = m.substitutions[vk]
            if callable(val):
                continue
            try:
                fval = _val_to_float(val, vk)
            except (TypeError, ValueError, AssertionError):
                continue
            unit_str = vk.unitrepr if vk.unitrepr and vk.unitrepr != "-" else None
            if unit_str:
                spec = f"{_format_subs_number(fval)} {unit_str}"
                var_lines.append(f'{vk.name} = "{spec}"')
            else:
                var_lines.append(f"{vk.name} = {_format_subs_number(fval)}")

        if var_lines:
            lines.append(f"[{path_str}]")
            lines.extend(var_lines)
            lines.append("")

    return _emit_lines(lines, path)


def load_subs(path):
    """Load a gpkit substitutions TOML file.

    Parameters
    ----------
    path : str, Path, or binary file-like
        File to load.  Must have been written by :func:`save_subs` (i.e.
        contain ``_gpkit_subs = true``).

    Returns
    -------
    dict
        Nested ``{lineage_path: {var_name: pint.Quantity | float}}``.
        Top-level keys are dotted model paths (e.g. ``"Mission.Aircraft"``).
    """
    if hasattr(path, "read"):
        doc = tomllib.load(path)
    else:
        with open(path, "rb") as f:
            doc = tomllib.load(f)

    if not doc.get(_GPKIT_SUBS_KEY):
        raise TomlParseError(
            f"File does not appear to be a gpkit subs file "
            f"(missing or false '{_GPKIT_SUBS_KEY}' key)"
        )

    result = {}
    _flatten_subs(doc, "", result)
    return result


def _flatten_subs(node, prefix, result):
    """Recursively flatten the TOML nested dict into {dotted_path: {name: value}}."""
    var_items = {}
    for key, val in node.items():
        if key == _GPKIT_SUBS_KEY:
            continue
        if isinstance(val, dict):
            child_prefix = f"{prefix}.{key}" if prefix else key
            _flatten_subs(val, child_prefix, result)
        else:
            # Leaf — treat as a variable spec
            try:
                float_val, units_str, _ = _parse_var_spec(val)
            except (TomlParseError, TypeError, ValueError):
                warnings.warn(
                    f"gpkit.toml.load_subs: could not parse '{key} = {val!r}', skipping"
                )
                continue
            if float_val is None:
                continue  # free variable (no value)
            var_items[key] = qty(units_str) * float_val if units_str else float_val

    if var_items and prefix:
        result[prefix] = var_items


def apply_subs(model, path_or_dict):
    """Apply substitutions from a TOML file (or pre-loaded dict) to a model in-place.

    Matches by lineage path and variable name.  Unknown lineage paths or
    variable names are skipped with a :mod:`warnings` warning, making this
    safe to use as the model evolves over time.

    Parameters
    ----------
    model : Model
        Model to modify in-place.
    path_or_dict : str, Path, or dict
        Either a path to a subs TOML file (passed to :func:`load_subs`) or a
        dict already returned by :func:`load_subs`.
    """
    if isinstance(path_or_dict, (str, Path)):
        subs = load_subs(path_or_dict)
    else:
        subs = path_or_dict

    # Build lineage_path → model map
    model_map = {}
    for m in [model] + list(model.walk()):
        if m.lineage:
            model_map[_lineage_path(m)] = m

    for lineage_path, var_dict in subs.items():
        m = model_map.get(lineage_path)
        if m is None:
            warnings.warn(
                f"gpkit.toml.apply_subs: no model found for lineage path "
                f"'{lineage_path}', skipping section"
            )
            continue

        for var_name, value in var_dict.items():
            matches = [vk for vk in m.unique_varkeys if vk.name == var_name]
            if len(matches) == 1:
                model.substitutions[matches[0]] = value
            elif len(matches) == 0:
                warnings.warn(
                    f"gpkit.toml.apply_subs: '{lineage_path}.{var_name}' not found "
                    f"in model, skipping"
                )
            else:
                warnings.warn(
                    f"gpkit.toml.apply_subs: '{lineage_path}.{var_name}' is ambiguous "
                    f"({len(matches)} matches), skipping"
                )
